spring.application.name=springboot_crud_operations

spring.datasource.url=jdbc:mysql://localhost:3306/demo
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Optional (Hibernate auto-detects dialect now)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Optional
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.server.port=9595

management.endpoints.web.exposure.include=health

management.endpoints.health.show.details = always

